name: LegendaryGuild
main: com.legendaryrealms.LegendaryGuild.LegendaryGuild
version: 5.1.0
api-version: 1.19
depend:
  - Vault
  - PlaceholderAPI
softdepend:
  - PlayerPoints
  - AttributePlus
  - SX-Attribute
commands:
  legendaryguild:
    aliases:
      - lguild
      - guild
      - guilds
      - lg