name: LegendaryGuild
main: com.legendaryrealms.LegendaryGuild.LegendaryGuild
version: 5.1.6
api-version: 1.14
depend:
  - Vault
  - PlaceholderAPI
  - ProtocolLib
softdepend:
  - PlayerPoints
  - AttributePlus
  - SX-Attribute
commands:
  legendaryguild:
    aliases:
      - lguild
      - guild
      - guilds
      - lg