name: LegendaryGuild
main: com.legendaryrealms.LegendaryGuild.LegendaryGuild
version: 5.0.1
api-version: 1.19
depend:
  - Vault
  - PlaceholderAPI
softdepend:
  - PlayerPoints
commands:
  legendaryguild:
    aliases:
      - lguild
      - guild
      - guilds
      - lg