#当玩家加入一个公会默认的职位ID
default: 普通成员
#公会会长的职位ID （请不要更改）
owner: 会长
#职位列表（按格式向下添加）
positions:
  会长:
    #职位权重 用于成员列表界面的按公会职位排序
    weight: 0
    #展示名称
    display: '&6会长'
    #buff （需Buff.yml中开启该模块功能才生效）
    attrs:
      - '攻击力 +20'
  普通成员:
    weight: 3
    display: '&f普通成员'
    attrs: []
    #是否可以同意入会申请
    accept: false
    #是否可以踢出公会成员
    kick: false
  精英成员:
    weight: 2
    display: '&a精英成员'
    #最多可以任命多少个该职位的人数
    max: 5
    attrs:
      - '攻击力 +10'
    accept: false
    kick: false
  长老:
    weight: 1
    display: '&e长老'
    max: 2
    attrs:
      - '攻击力 +15'
    accept: true
    kick: true