#是否启用该功能
#设置为false 则关闭公会仓库这个功能
enable: true
settings:
  #每个仓库的标题
  title: '&e%id% &0号仓库'
  #每个仓库的尺寸 （9，18，27，36，45，54）
  size: 54
  #每个公会等级最多可以解锁多少个仓库
  #可继续向下添加，但不超过 config.yml 中设定的最大公会等级
  store_amount:
    0: 1
    1: 3
    2: 5
    3: 7
    4: 10
    5: 20
  #解锁一个新的仓库需要的花费
  unlock:
    requirements:
      - 'guild_money;5000'
  #限制不能放入的物品
  limits:
    #当物品含有指定lore时
    contains-lore:
      #是否启用
      enable: true
      #需完全匹配
      list:
        - '&c绑定'
    #限制指定id物品放入
    materials:
      enable: true
      #填写物品id
      list:
        - BEDROCK
    #限制指定物品名称放入
    display:
      enable: true
      #需完全匹配
      list:
        - '&c测试物品'