#是否启用该功能
#设置为false 则关闭公会仓库这个功能
enable: true
settings:
  #每个仓库的标题
  title: '&e%id% &0号仓库'
  #每个仓库的尺寸 （9，18，27，36，45，54）
  size: 54
  #每个公会等级最多可以解锁多少个仓库
  #可继续向下添加，但不超过 config.yml 中设定的最大公会等级
  store_amount:
    0: 1
    1: 3
    2: 5
    3: 7
    4: 10
    5: 20
  #解锁一个新的仓库需要的花费
  unlock:
    requirements:
      - 'guild_money;5000'